"""Atualizando a tabela Event_Item

Revision ID: 1ad915a11275
Revises: e4fe36a617dc
Create Date: 2026-08-05 09:24:17.719398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad915a11275'
down_revision: Union[str, None] = 'e4fe36a617dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_items', sa.Column('code', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_event_items_code'), 'event_items', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_items_code'), table_name='event_items')
    op.drop_column('event_items', 'code')
    # ### end Alembic commands ###
