"""change stock movement dates to datetime

Revision ID: 6a9c730bae3f
Revises: 6cbde48d9501
Create Date: 2026-08-17 12:40:21.655747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9c730bae3f'
down_revision: Union[str, None] = '6cbde48d9501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
