"""criar de tabelas users

Revision ID: 99cfbc2c0e43
Revises: e8f70ea9557b
Create Date: 2026-08-04 14:33:09.871234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99cfbc2c0e43'
down_revision: Union[str, None] = 'e8f70ea9557b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
