"""criando a tabela categoria

Revision ID: b9c24572d8eb
Revises: 99cfbc2c0e43
Create Date: 2026-08-04 15:02:42.365701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c24572d8eb'
down_revision: Union[str, None] = '99cfbc2c0e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
