"""dependence: product e movement

Revision ID: cdf8d36dc1ec
Revises: fd9c260ad0fb
Create Date: 2026-08-18 01:36:19.271402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf8d36dc1ec'
down_revision: Union[str, None] = 'fd9c260ad0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stock_movements_product_id_fkey', 'stock_movements', type_='foreignkey')
    op.create_foreign_key(None, 'stock_movements', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.create_foreign_key('stock_movements_product_id_fkey', 'stock_movements', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
